### ISSUE TITLE
what are the difference between final assembly A and B?

### ISSUE THREAD

**Issue by lizihe21** [HMPNK/CSA2.6#2]
I was using a prepared assembly genome as the input starting from the 02 step,and finally i get two version of assembly varying huge in scaffold numbers.Why are there two difference version of assembly and what are the difference between them.

**Comment by HMPNK** [comment]
I guess you used parameter '- x off'?
Assembly A will be the assembly without guessed edges from Ragout tool resulting in more scaffolds, but higher accuracy. Assembly B is using the guessed edges and results in larger scaffolds but may contain few more misassemblies. If you have a closely related reference use '-x on' .

Thanks for feedback! How was your assembly going, did it improve much?

**Comment by HMPNK** [comment]
By closely related I mean a divergence time of ~20MYA. For birds and fishes maybe even 65MYA.

**Comment by lizihe21** [comment]
Both results improve much.Assemble B generate the same amount of chromesome as the organism should have, but some errors emerge after a synteney analysis.Its a great tool.Thanks a lot!
