### ISSUE TITLE
problem if system language not en_US.UTF-8

### ISSUE THREAD

**Issue by smrtin** [HMPNK/CSA2.6#4]
Hi,
we stumbled across a little problem with the your script 03_REASSEMBLE.pl . We were using your pipeline on a Centos-7 system, where the language was not set to en_US.UTF-8. This led to an error in step 3 because the script tried to process a file called 'insgesamt', which it could not find. 
We narrowed it down to the line 100, where you use a ' xargs wc -l | sort -k1,1rn | grep -vw total' .

We came up with a solution to set the system language in the beginning of the STEP_03.bash-skript. 
export LANG='en_US.UTF-8'

Maybe you can think of a different solution or mention it in the Readme.
Thanks again for this nice Pipeline!

**Comment by HMPNK** [comment]
Thanks Sebastian, for finding this bug and a providing a quick solution. I will add this to the README section.
